name: CI/CD Process

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # , windows-latest]
        java: ['21', '25']
    defaults:
      run:
        shell: bash 
    steps:
      - &checkout
        name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - &setup-java
        name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - &mill-cache
        name: Cache Mill dependencies
        uses: coursier/cache-action@bebeeb0e6f48ebad66d3783946588ecf43114433 # v7.0.0
      - name: Build Project
        run: ./mill __.compile
      - name: Run Tests
        run: ./mill __.test

  qa:
    name: Code Quality Analysis
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # , windows-latest]
        java: ['21', '25']
    defaults:
      run:
        shell: bash 
    steps:
      - *checkout
      - *setup-java
      - *mill-cache
      - name: Run Code Quality Analysis
        run: |
          ./mill __.fix --check
          ./mill mill.scalalib.scalafmt/checkFormatAll
        
  success:
    runs-on: ubuntu-24.04
    needs:
      - qa
      - build
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}      